config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :albums do
    resources :photos
  end
  resources :photos
  resources :albums
  resources :pages
  root to: 'photos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :photos
    belongs_to :user
    validates :title, :description, :mode, presence: true
    validates :title, length: { maximum: 140 }
    validates :description, length: { maximum: 300 }
    enum mode: [:public_mode, :private_mode] 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/normal_user.rb
class NormalUser < User
end

app/models/photo.rb
class Photo < ApplicationRecord
    mount_uploader :image, PhotosUploader
    belongs_to :album, optional: true
    belongs_to :user
    validates :title, :description, :mode, :image, presence: true
    validates :title, length: { maximum: 140 }
    validates :description, length: { maximum: 300 }
    enum mode: [:public_mode, :private_mode] 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :albums
  has_many :photos
  validates :email, :encrypted_password, :firstname, :lastname, presence: true
  validates :firstname, :lastname, length: { maximum: 25 }
  validates :email, length: {maximum: 255}
  validates :email, format: { with: /\A\S+@.+\.\S+\z/, message: "must be email" }
  validates :password, length: { maximum:64 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def index
        @albums = Album.where(mode: "public_mode")
    end

    def new 
        @album = current_user.albums.new
    end

    def create
        params[:album][:mode] = params[:album][:mode].to_i
        @album = current_user.albums.new(album_params)
        if @album.save
            flash[:success] = "Photo has been uploaded!"
            redirect_to new_album_path
        else
            flash[:error] = "Error upload"
            render :new
        end
    end
    private 
        def album_params 
            params.require(:album).permit!
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout false
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
        def configure_permitted_parameters
            added_attrs = [:firstname, :lastname, :email, :password, :password_confirmation, :remember_me]
            devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
            devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @photos = current_user.photos.all
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :get_photo, only: [:edit, :update, :destroy]
    def index
        @photos = Photo.where(mode: "public_mode")
    end

    def new
        @photo = current_user.photos.new
    end

    def create
        params[:photo][:mode] = params[:photo][:mode].to_i 
        @photo = current_user.photos.new(photo_params)
        if @photo.save
            redirect_to photos_path
        else
            flash[:error] = "Error adding photos!"
            render :new
        end
    end

    def edit
    end

    def update 
        params[:photo][:mode] = params[:photo][:mode].to_i 
       if @photo.update(photo_params)
        redirect_to pages_path
       else
        flash[:error] = "Error edited!"
        redirect_to :edit
       end
    end

    def destroy
        if @photo.destroy
            flash[:success] = "Photo has been deleted!"
            redirect_to pages_path
        else
            flash[:error] = "Error delete"
            render :edit
        end
    end

    private
        def photo_params
            params.require(:photo).permit!
        end

        def get_photo
            @photo = current_user.photos.find(params[:id])
        end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'new_album', 'menu' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  <%= render 'shared/menu' %>
  <div id="content" class="container-fluid">
     <div class="row">
         <div class="left col-2">
             <div class="menu-left d-flex flex-column justify-content-center">
                 <a href="#">Feeds</a>
                 <a href="#">Discover</a>
             </div>
         </div>
         <div class="middle col-8">
            <div class="head d-flex justify-content-between">
                <div class="title">New Album</div>
                <div class="button">
                    <a href="#" class="btn">Back</a>
                </div>
            </div>
            <hr>
              <% if flash[:success] %>
                    <div class="alert alert-success">
                        <%= flash[:success] %>
                    </div>
                <% end %>
                <% if flash[:error] %>
                     <div class="alert alert-danger">
                        <%= flash[:error] %>
                    </div>
                <% end %>
            <div class="body d-flex justify-content-around">
                <div class="body-content">
                    <%= form_for @album do |f| %>
                        <div>
                            <%= f.label :title, "Title", class: "title" %>
                            <%= f.text_field :title, class: "form-control" %>
                        </div>
                        
                        <div style="margin-top: 31px;">
                            <%= f.label :mode, "Sharing mode", class: "title" %><br>
                            <%= f.select :mode, [["Public", "0"], ["Private", "1"]], class: "form-control" %>
                        </div>
                        
                        <div class="body-img" style="margin-top: 31px;">
                            <%= f.file_field :image %>
                            <i class="fa fa-plus"></i>
                            <img src="" alt="">
                        </div>

                        <div class="body-content">
                            <%= f.label :description, "Description" %>
                            <%= f.text_area :description, class: "form-control" %>
                        </div>

                        <div class="body-button d-flex" style="margin-top: 51px;">
                            <%= f.submit "Save", class: "btn"%>
                        </div>
                    <% end %>

            </div>
         </div>
         <div class="right col-2"></div>
     </div>
  </div>
</body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.js"></script> 
    <%= javascript_pack_tag 'new_album' %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Internship</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'profile', 'menu' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<body>
  <%= render 'shared/menu' %>
  <div id="content" class="container-fluid">
     <div class="row">
         <div class="left col-2">
             <div class="menu-left d-flex flex-column justify-content-center">
                 <a href="#">Feeds</a>
                 <a href="#">Discover</a>
             </div>
         </div>
         <div class="middle col-8">
            <div class="top-content d-flex">
                <div class="avartar">
                    <a href="#"><img class="rounded-circle" src="images/4wvuq0i4ozs1q.jpg" alt="" width="171px" height="171px"></a>
                </div>
                <div class="info-user">
                    <div class="follow">following</div>
                    <div class="name-user">Hansford Nguyen</div>
                    <div class="info-detail">
                        <a href="#"><%= current_user.photos.size %> <span>PHOTOS</span></a> | 
                        <a href="#"><%= current_user.albums.size %> <span>ALBUMS</span></a> | 
                        <a href="#">22 <span>FOLLOWINGS</span></a> | 
                        <a href="#">13 <span>FOLLOWERS</span></a> | 
                    </div>
                </div>
                <button type="button" class="btn" onclick="window.location.href='<%= new_photo_path %>'">Add Photo</button>
            </div>
             <% if flash[:success] %>
            <div class="alert alert-success">
                <%= flash[:success] %>
            </div>
            <% end %>
            <div class="bottom-content">
                <div class="d-flex d-flex flex-wrap">
                    <% @photos.each do |photo| %>
                    <div class="picture-info">
                        <div class="picture">
                            <div class="key">
                                <% if photo.private_mode? %>
                                <button class="d-flex justify-content-center"><i class="fa fa-lock"></i></button>
                                <% end %>
                            </div>
                            <div class="edit"><button class="btn d-flex justify-content-center" onclick="window.location.href='<%= edit_photo_path(photo) %>' " >EDIT</button></div>
                            <a class="img-fluid" href="#"><img src="<%= photo.image.url %>" alt="" width="185px" height="185px"></a>
                        </div>
                        <div class="title"><%= photo.title %></div>
                    </div>
                    <% end %>
                </div>

              
                
            </div>
         </div>
         <div class="right col-2"></div>
     </div>
  </div>
</body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 
</html>

app/views/photos/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'edit_photo', 'menu' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  <%= render 'shared/menu' %>
  <div id="content" class="container-fluid">
     <div class="row">
         <div class="left col-2">
             <div class="menu-left d-flex flex-column justify-content-center">
                 <a href="#">Feeds</a>
                 <a href="#">Discover</a>
             </div>
         </div>
         <div class="middle col-8">
            <div class="head d-flex justify-content-between">
                <div class="title">Edit Photo</div>
                <div class="button">
                    <a href="#" class="btn">Back</a>
                </div>
            </div>
            <hr>
            <% if flash[:error] %>
             <div class="alert alert-danger">
                <%= flash[:error] %>
            </div>
            <% end %>
            <div class="body d-flex justify-content-around">
                <div class="body-content">
                   

                     <%= form_for @photo do |f| %>
                        <div>
                            <%= f.label :title, "Title", class: "title" %>
                            <%= f.text_field :title, class: "form-control" %>
                        </div>
                        
                        <div style="margin-top: 31px;">
                            <%= f.label :mode, "Sharing mode", class: "title" %><br>
                            <%= f.select :mode, [["Public", "0"], ["Private", "1"]], class: "form-control" %>
                        </div>
                        
                        <div class="body-img" style="margin-top: 31px;">
                            <%= f.file_field :image %>
                            <i class="fa fa-plus"></i>
                            <img src="<%= @photo.image.url %>" alt="" width="180px" height="180px">
                        </div>

                        <div class="body-content">
                            <%= f.label :description, "Description", class: "title" %>
                            <%= f.text_area :description, class: "form-control" %>
                        </div>

                        <div class="body-button d-flex" style="margin-top: 51px;">
                            <%= f.submit "Save", class: "btn"%>
                        </div>
                    <% end %>
                    <form>  
                        
                    </form>
                     <div class="body-button d-flex" style="margin-top: 51px;">
                        <%= button_to "Delete", @photo, method: :delete, class: "delete" %>
                    </div>

                </div>
            </div>
         </div>
         <div class="right col-2"></div>
     </div>
  </div>
</body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.js"></script> 
    <%= javascript_pack_tag 'new_photo' %>
</html>

app/views/photos/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'photo', 'menu' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <%= render 'shared/menu' %>
  <div id="content" class="container-fluid">
     <div class="row">
         <div class="left col-2"></div>
         <div class="middle col-8">
             <div class="button-menu d-flex justify-content-center" style="margin-bottom: 20px;">
                 <div class="btn-group">
                     <a href="<%= photos_path %>" class="btn">PHOTO</a>
                     <a href="<%= albums_path %>" class="btn">ALBUM</a>
                 </div>
             </div>
             <div class="main-content">
                 <div class="row" style="margin-bottom: 15px;">
                    <% i = 0 %>
                    <% @photos.each do |photo| %>
                     <div class="col-lg-6 col-md-12 col-sm-12" style="margin-bottom: 20px;">
                         <div class="row">
                             <div class="col-6" style="padding-right: 0px;">
                                 <div class="picture" data-toggle="modal" data-target="#myModal-<%= i %>">
                                    <a href="#"><img src="<%= photo.image.url %>" alt="Anh chan dung" width="100%" height="100%"></a>
                                 </div>
                             </div>
                             <div class="col-6" style="padding-left: 0px;">
                                 <div class="info" style="padding: 10px">
                                     <div class="user-name d-flex">
                                         <div class="user-icon d-flex justify-content-center"><%= photo.user.firstname[0] %><%= photo.user.lastname[0] %></div>
                                         <div class="name"><%= photo.user.firstname %> <%= photo.user.lastname %></div>
                                     </div>
                                     <div class="title"><%= photo.title %></div>
                                     <div class="para"><%= photo.description %></div>
                                     <div class="day-post d-flex">
                                         <div class="icon-heart"><i class="fa fa-heart"></i></div>
                                         <div class="number-likes">123</div>
                                         <div class="time"><%= photo.created_at %></div>
                                     </div>
                                 </div>
                             </div>
                         </div>

                         <!-- The Modal -->
                         <div class="modal fade" id="myModal-<%= i %>">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <div class="title"><%= photo.title %></div>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <img src="<%= photo.image.url %>" alt="Anh chan dung" width="100%" height="100%">
                                    </div>
                                    <div class="modal-footer">
                                        <div class="para"><%= photo.description %></div>
                                    </div>
                                </div>
                            </div>
                         </div>
                     </div>
                     <% i = i + 1 %>
                    <% end %>
             </div>
             <div class="spiner d-flex justify-content-lg-center">
                <div class="spinner-border" style="width: 49px; height: 49px;"></div>
             </div>
         </div>
         <div class="right col-2"></div>
     </div>
  </div>
</body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 
</html>

app/views/photos/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'new_photo', 'menu' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  <%= render 'shared/menu' %>
  <div id="content" class="container-fluid">
     <div class="row">
         <div class="left col-2">
             <div class="menu-left d-flex flex-column justify-content-center">
                 <a href="#">Feeds</a>
                 <a href="#">Discover</a>
             </div>
         </div>
         <div class="middle col-8">
            <div class="head d-flex justify-content-between">
                <div class="title">New Photo</div>
                <div class="button">
                    <a href="#" class="btn">Back</a>
                </div>
            </div>
            <hr>
            <div class="body d-flex justify-content-around">
                <div class="body-content">
             

                    <%= form_for @photo do |f| %>
                        <div>
                            <%= f.label :title, "Title", class: "title" %>
                            <%= f.text_field :title, class: "form-control" %>
                        </div>
                        
                        <div style="margin-top: 31px;">
                            <%= f.label :mode, "Sharing mode", class: "title" %><br>
                            <%= f.select :mode, [["Public", "0"], ["Private", "1"]], class: "form-control" %>
                        </div>
                        
                        <div class="body-img" style="margin-top: 31px;">
                            <%= f.file_field :image %>
                            <i class="fa fa-plus"></i>
                            <img src="" alt="">
                        </div>

                        <div class="body-content">
                            <%= f.label :description, "Description" %>
                            <%= f.text_area :description, class: "form-control" %>
                        </div>

                        <div class="body-button d-flex" style="margin-top: 51px;">
                            <%= f.submit "Save", class: "btn"%>
                        </div>
                    <% end %>

            </div>
         </div>
         <div class="right col-2"></div>
     </div>
  </div>
</body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.js"></script> 
    <%= javascript_pack_tag 'new_photo' %>
</html>

app/views/shared/_menu.html.erb
 <div id="menu" class="container-fluid">
      <div class="menu-item">
          <div class="menu-item-logo"> 
            <a href="#" style="font-size: 20px; font-weight: bold; color: white; text-decoration: none;">Fotobook</a>
          </div>
          <div class="menu-item-form">
            <form action="#">
                <input type="text" placeholder="Search Photo / Album">
            </form>
          </div>
      </div>
        <div class="menu-item">
            <% if user_signed_in? %>
            <a href="<%= pages_path %>" class="user-info d-flex">
                <div class="logo-user"><%= current_user.firstname[0] %><%= current_user.lastname[0] %></div>
                <div class="name-user"><%= current_user.firstname %> <%= current_user.lastname %> </div>
            </a>
            <% end %>
            <% if user_signed_in? %>
              <%= link_to "Logout", destroy_user_session_path, :method => :delete , class: "login-logout" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "login-logout" %>
            <% end %>
        </div>
  </div>